### ISSUE TITLE
How did you get into programming?

### ISSUE THREAD

**Issue by arthurvr** [mollikka/ama#1]

**Comment by mollikka** [comment]
My father has been programming for as long as it has been affordable in a Finnish household.
He taught me to use desktop computers from a very young age. When I was in elementary school, he let me play with his old Commodore 64 and Apple Classic. So I grew up with an interest in computers.

I think I really started to understand programming logic when I started making games in [Game Maker](https://en.wikipedia.org/wiki/GameMaker:_Studio). I think I was 12 or 13 years old at the time. In 8th grade our basic Pascal programming classes started in school and I remember rushing the exercises so I could spend time writing games instead...

When it came time to apply for higher education, it felt pretty natural to pick Computer Science and Engineering. So there was never really a moment when I discovered programming. I just grew into it.

**Comment by arthurvr** [comment]
Cool! :+1:
