### ISSUE TITLE
What's your favorite movie or TV show?

### ISSUE THREAD

**Issue by arthurvr** [mollikka/ama#11]

**Comment by mollikka** [comment]
I watch a lot of TV, and there are many shows I have enjoyed. I usually don't rewatch shows, so it's a little hard to answer this question. Doctor Who is quite nice and I keep coming back for more, and the same goes for Friendship is Magic. I remember really enjoying Buffy the Vampire Slayer, too. So maybe I could call those my favorite TV shows?

I guess if I have to pick just one movie or TV show, I'm going to go with Terminator 2. It's a really enjoyable film that I can still watch every few years without getting bored!
![](http://1.bp.blogspot.com/_HWhYup01zdk/TJHFfdo0dgI/AAAAAAAAAxQ/XTmjEg9zcUk/s1600/t2.png)
