### ISSUE TITLE
What do you think about Spain?

### ISSUE THREAD

**Issue by aarroyoc** [mollikka/ama#12]
How do people from outside Spain thinks about Spain? and How do you think about Spain?

**Comment by mollikka** [comment]
Spain has been a high culture nation for centuries. The language is one of the biggest in the world (and personally I think it's a very pleasant language to listen to). From what I understand, Spain contributed greatly to development of modern Chess, for which I'm grateful. I don't follow Football but Spain is strong in that area, too.

I have the impression that there's some separatist unease going on, but honestly I haven't been following Spanish politics.

I think us Finns as people don't have that close relations to Spain, although there's a fair amount of Finns living in southern Spain. Spain is rarely in the news.

I was actually just discussing going to Spain in near future! Hopefully I get to go there soon.
