### ISSUE TITLE
What's your favorite gif?

### ISSUE THREAD

**Issue by arthurvr** [mollikka/ama#2]

**Comment by mollikka** [comment]
I'm a big fan of [/r/perfectloops](http://www.reddit.com/r/perfectloops) and [/r/loadingicon](http://www.reddit.com/r/loadingicon/)
I find a new "favorite gif" in those subreddits almost every day, so it really depends on when you're asking.

But there is this one 'reaction gif' that find hilarious and never seem to get enough of. So I'll have to go with this one:
![](https://i.imgur.com/UyZuJKa.gif)
