### ISSUE TITLE
What's your favorite word?

### ISSUE THREAD

**Issue by arthurvr** [mollikka/ama#3]

**Comment by mollikka** [comment]
_Shenanigans_ is a beautiful word that rolls off the tongue. Even if you don't know the definition, it sounds like secret whispers and clothes quietly rubbing on each other as a shadowy figure sneaks around the corner. Shenanigans are the hooks and the turning points of great stories, and the build-ups and punch lines of comedies.

_Shenanigans_ are how the world turns.
