### ISSUE TITLE
What's the most beautiful place of Finland?

### ISSUE THREAD

**Issue by arthurvr** [mollikka/ama#4]

**Comment by mollikka** [comment]
On a rock next to a natural Finnish lake. Clean Finnish water is something special.

Honorable mention: the room upstairs in Ateneum Art Museum with [Taistelevat metsot](https://fi.wikipedia.org/wiki/Taistelevat_metsot#/media/File:Ferdinand_von_Wright_-_Taistelevat_metsot_-_1886_-_oljymaalaus_-_Ateneumin_taidemuseo.png) in it. It's a huge painting, almost two meters wide!
