### ISSUE TITLE
What kind of camera do you use?

### ISSUE THREAD

**Issue by sindresorhus** [mollikka/ama#5]

**Comment by mollikka** [comment]
I use a Canon EOS 650D. It's a decent DSLR camera. I have three lenses for it (70-300mm), (15-85mm), and (10-22mm). Oh, and a low-tier tilt-shift lens.

Honestly I'm not one of those people who spend hours comparing camera hardware, I just like taking pictures :)

**Comment by sindresorhus** [comment]
> Honestly I'm not one of those people who spend hours comparing camera hardware, I just like taking pictures :)

:+1:
