### ISSUE TITLE
What do you think about Norway?

### ISSUE THREAD

**Issue by sindresorhus** [mollikka/ama#7]

**Comment by mollikka** [comment]
I've never been in Norway, but I'd like to go some day. The scenery looks amazing and unique in pictures. I think I've never seen a photo of Norway's nature that I didn't like.

My brother knows a lot about Viking history and mythology. He often educates me on those things, it's very fascinating. 

Geopolitically Norway is in a very unique place, which makes it hard to compare it to other countries. From what I understand,  it's a good place to live in, overall.

P.S.
I find it odd that the whole western world holds the Nobel Peace Prize in so high regard. Doesn't seem like something a national parliament should be able to dictate. But good for you, I guess! :)
